name: Cost Analysis

on:
  schedule:
    - cron: '0 2,6 * * *'  # UTC时间2点和6点，对应北京时间10点和14点
  workflow_dispatch:  # 添加手动触发支持

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run cost analysis
        run: python main.py --strategy cost --code 600004 --cost 9.6
        
      - name: Commit and push if changed
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update cost analysis results" && git push)