name: Daily Stock Analysis

on:
  schedule:
    - cron: '30 1 * * *'  # UTC时间1:30，对应北京时间9:30
  workflow_dispatch:  # 允许手动触发

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run analysis
      run: python main.py
    
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: stock-analysis-${{ steps.date.outputs.date }}
        release_name: Stock Analysis Report ${{ steps.date.outputs.date }}
        draft: false
        prerelease: false
    
    - name: Upload Log to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./logs/stock_analysis_${{ steps.date.outputs.date }}.log
        asset_name: stock_analysis_${{ steps.date.outputs.date }}.log
        asset_content_type: text/plain

    - name: Upload Selected Stocks to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./stocks/stocks_${{ steps.date.outputs.date }}.txt
        asset_name: stocks_${{ steps.date.outputs.date }}.txt
        asset_content_type: text/plain