name: Daily Stock Analysis

on:
  schedule:
    - cron: '30 1 * * *'  # UTC时间1:30，对应北京时间9:30
  workflow_dispatch:  # 允许手动触发

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        strategy: [double_ma, ma]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run analysis
      run: python main.py --strategy ${{ matrix.strategy }}
    
    - name: Get current date and time
      id: datetime
      run: |
        echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        echo "timestamp=$(date +'%H-%M-%S')" >> $GITHUB_OUTPUT
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: stock-analysis-${{ steps.datetime.outputs.date }}-${{ steps.datetime.outputs.timestamp }}
        release_name: Stock Analysis Report ${{ steps.datetime.outputs.date }}
        draft: false
        prerelease: false
    
    - name: Get file lists
      id: files
      run: |
        echo "logs=$(ls -1 logs/)" >> $GITHUB_OUTPUT
        echo "stocks=$(ls -1 stocks/)" >> $GITHUB_OUTPUT
    
    outputs:
      release_url: ${{ steps.create_release.outputs.upload_url }}
      logs: ${{ steps.files.outputs.logs }}
      stocks: ${{ steps.files.outputs.stocks }}

  upload-logs:
    needs: analyze
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.analyze.outputs.logs) }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Upload Log Files
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.analyze.outputs.release_url }}
        asset_path: ./logs/${{ matrix.file }}
        asset_name: ${{ matrix.file }}
        asset_content_type: text/plain

  upload-stocks:
    needs: analyze
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.analyze.outputs.stocks) }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Upload Stock Files
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.analyze.outputs.release_url }}
        asset_path: ./stocks/${{ matrix.file }}
        asset_name: ${{ matrix.file }}
        asset_content_type: text/plain