name: Daily Stock Analysis

on:
  schedule:
    - cron: '0 1 * * 1-5'  # UTC时间1:00（北京时间9:00），仅在工作日运行
  workflow_dispatch:  # 允许手动触发

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run stock analysis
        run: python main.py

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.date.outputs.date }}
          release_name: Stock Analysis Report ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false

      - name: Upload logs
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./logs/stock_analysis_${{ steps.date.outputs.date }}.log
          asset_name: stock_analysis_${{ steps.date.outputs.date }}.log
          asset_content_type: text/plain

      - name: Upload MA strategy results
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./stocks/ma_stocks_${{ steps.date.outputs.date }}.txt
          asset_name: ma_stocks_${{ steps.date.outputs.date }}.txt
          asset_content_type: text/plain

      - name: Upload Double MA strategy results
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./stocks/double_ma_stocks_${{ steps.date.outputs.date }}.txt
          asset_name: double_ma_stocks_${{ steps.date.outputs.date }}.txt
          asset_content_type: text/plain