name: Double MA Analysis

on:
  schedule:
    - cron: '0 1 * * *' 
  workflow_dispatch:  # 允许手动触发

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run stock analysis
        run: python main.py

      - name: Get current date and time
        id: datetime
        env:
          TZ: Asia/Shanghai
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "timestamp=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT

      - name: Get Latest Release
        id: get_release
        uses: actions/github-script@v6
        with:
          script: |
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: 'AnalysisResults'
            });
            core.setOutput('upload_url', release.data.upload_url);

      - name: Upload logs
        if: hashFiles('./logs/stock_analysis.log') != ''
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./logs/stock_analysis.log
          asset_name: stock_analysis_${{ steps.datetime.outputs.timestamp }}.log
          asset_content_type: text/plain

      - name: Upload Double MA strategy results
        if: hashFiles('./stocks/double_ma_stocks.txt') != ''
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./stocks/double_ma_stocks.txt
          asset_name: double_ma_stocks_${{ steps.datetime.outputs.timestamp }}.txt
          asset_content_type: text/plain
